/*
 * Copyright (C) 2014-2015 Stichting Mapcode Foundation (http://www.mapcode.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */ 
#ifndef __MAPCODE_TERRITORY_ALPHABETS_H__
#define __MAPCODE_TERRITORY_ALPHABETS_H__


// *** GENERATED FILE (coords.cpp), DO NOT CHANGE OR PRETTIFY ***

#ifdef __cplusplus
extern "C" {
#endif

#include "basics.h"
#include "mapcode_alphabets.h"

static const TerritoryAlphabets alphabetsForTerritory[MAX_CCODE] = {
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 0 VAT Vatican City State
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 1 MCO Monaco
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 2 GIB Gibraltar
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 3 TKL Tokelau
    {2, {MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_ARABIC}}, // 4 CCK Cocos Islands
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 5 BLM Saint-Barthelemy
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 6 NRU Nauru
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 7 TUV Tuvalu
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 8 MAC Macau
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 9 SXM Sint Maarten
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 10 MAF Saint Martin
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 11 NFK Norfolk and Philip Island
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 12 PCN Pitcairn Islands
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 13 BVT Bouvet Island
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 14 BMU Bermuda
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 15 IOT British Indian Ocean Territory
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 16 SMR San Marino
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 17 GGY Guernsey
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 18 AIA Anguilla
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 19 MSR Montserrat
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 20 JEY Jersey
    {3, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 21 CXR Christmas Island
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 22 WLF Wallis and Futuna the
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 23 VGB British Virgin Islands
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 24 LIE Liechtenstein
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 25 ABW Aruba
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 26 MHL Marshall Islands
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 27 ASM American Samoa
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 28 COK Cook Islands
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 29 SPM Saint Pierre and Miquelon
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 30 NIU Niue
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 31 KNA Saint Kitts and Nevis, Federation of
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 32 CYM Cayman islands
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 33 BES Bonaire, St Eustasuis and Saba
    {2, {MAPCODE_ALPHABET_THAANA, MAPCODE_ALPHABET_ROMAN}}, // 34 MDV Maldives
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 35 SHN Saint Helena, Ascension and Tristan da Cunha
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 36 MLT Malta
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 37 GRD Grenada
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 38 VIR Virgin Islands of the United States
    {2, {MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_ARABIC}}, // 39 MYT Mayotte
    {2, {MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_CYRILLIC}}, // 40 SJM Svalbard and Jan Mayen
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 41 VCT Saint Vincent and the Grenadines
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 42 HMD Heard Island and McDonald Islands
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 43 BRB Barbados
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 44 ATG Antigua and Barbuda
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 45 CUW Curacao
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 46 SYC Seychelles
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 47 PLW Palau
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 48 MNP Northern Mariana Islands
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 49 AND Andorra, Principality of
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 50 GUM Guam
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 51 IMN Isle of Mann
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 52 LCA Saint Lucia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 53 FSM Micronesia
    {3, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 54 SGP Singapore
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 55 TON Tonga
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 56 DMA Dominica, Commonwealth of
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 57 BHR Bahrain
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 58 KIR Kiribati
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 59 TCA Turks and Caicos Islands
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 60 STP Sao Tome and Principe
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 61 HKG Hong Kong
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 62 MTQ Martinique
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 63 FRO Faroe Islands
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 64 GLP Guadeloupe
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 65 COM Comoros, Union of the
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 66 MUS Mauritius
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 67 REU Reunion
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 68 LUX Luxembourg
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 69 WSM Samoa, Independent State of
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 70 SGS South Georgia and the South Sandwich Islands
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 71 PYF French Polynesia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 72 CPV Cape Verde
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 73 TTO Trinidad and Tobago
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 74 BRN Brunei
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 75 ATF French Southern and Antarctic Lands
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 76 PRI Puerto Rico
    {2, {MAPCODE_ALPHABET_GREEK, MAPCODE_ALPHABET_ROMAN}}, // 77 CYP Cyprus
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 78 LBN Lebanon
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 79 JAM Jamaica
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 80 GMB Gambia
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 81 QAT Qatar, State of
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 82 FLK Falkland Islands
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 83 VUT Vanuatu
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 84 MNE Montenegro
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 85 BHS Bahamas, Commonwealth of the
    {2, {MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_ARABIC}}, // 86 TLS Timor-Leste
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 87 SWZ Swaziland
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 88 KWT Kuwait, State of
    {2, {MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_DEVANAGARI}}, // 89 FJI Fiji
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 90 NCL New Caledonia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 91 SVN Slovenia
    {3, {MAPCODE_ALPHABET_HEBREW, MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 92 ISR Israel
    {3, {MAPCODE_ALPHABET_HEBREW, MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 93 PSE Palestinian territories
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 94 SLV El Salvador
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 95 BLZ Belize
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 96 DJI Djibouti
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 97 MKD Macedonia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 98 RWA Rwanda
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 99 HTI Haiti
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 100 BDI Burundi
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 101 GNQ Equatorial Guinea
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 102 ALB Albania
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 103 SLB Solomon Islands
    {2, {MAPCODE_ALPHABET_ARMENIAN, MAPCODE_ALPHABET_ROMAN}}, // 104 ARM Armenia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 105 LSO Lesotho
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 106 BEL Belgium
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 107 MDA Moldova
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 108 GNB Guinea-Bissau
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 109 TWN Taiwan
    {2, {MAPCODE_ALPHABET_TIBETAN, MAPCODE_ALPHABET_ROMAN}}, // 110 BTN Bhutan
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 111 CHE Switzerland
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 112 NLD Netherlands
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 113 DNK Denmark
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 114 EST Estonia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 115 DOM Dominican Republic
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 116 SVK Slovakia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 117 CRI Costa Rica
    {2, {MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_CYRILLIC}}, // 118 BIH Bosnia and Herzegovina
    {2, {MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_CYRILLIC}}, // 119 HRV Croatia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 120 TGO Togo
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 121 LVA Latvia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 122 LTU Lithuania
    {3, {MAPCODE_ALPHABET_SINHALESE, MAPCODE_ALPHABET_TAMIL, MAPCODE_ALPHABET_ROMAN}}, // 123 LKA Sri Lanka
    {3, {MAPCODE_ALPHABET_GEORGIAN, MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 124 GEO Georgia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 125 IRL Ireland
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 126 SLE Sierra Leone
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 127 PAN Panama
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 128 CZE Czech Republic
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 129 GUF French Guiana
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 130 ARE United Arab Emirates
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 131 AUT Austria
    {3, {MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ARABIC}}, // 132 AZE Azerbaijan
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 133 SRB Serbia
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 134 JOR Jordan
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 135 PRT Portugal
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 136 HUN Hungary
    {2, {MAPCODE_ALPHABET_KOREAN, MAPCODE_ALPHABET_ROMAN}}, // 137 KOR South Korea
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 138 ISL Iceland
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 139 GTM Guatemala
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 140 CUB Cuba
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 141 BGR Bulgaria
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 142 LBR Liberia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 143 HND Honduras
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 144 BEN Benin
    {3, {MAPCODE_ALPHABET_AMHARIC, MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 145 ERI Eritrea
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 146 MWI Malawi
    {2, {MAPCODE_ALPHABET_KOREAN, MAPCODE_ALPHABET_ROMAN}}, // 147 PRK North Korea
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 148 NIC Nicaragua
    {2, {MAPCODE_ALPHABET_GREEK, MAPCODE_ALPHABET_ROMAN}}, // 149 GRC Greece
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 150 TJK Tajikistan
    {2, {MAPCODE_ALPHABET_BENGALI, MAPCODE_ALPHABET_ROMAN}}, // 151 BGD Bangladesh, People's Republic of
    {2, {MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_ROMAN}}, // 152 NPL Nepal
    {3, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_TIFINAGH}}, // 153 TUN Tunisia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 154 SUR Suriname
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 155 URY Uruguay
    {2, {MAPCODE_ALPHABET_KHMER, MAPCODE_ALPHABET_ROMAN}}, // 156 KHM Cambodia
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 157 SYR Syria
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 158 SEN Senegal
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 159 KGZ Kyrgyzstan
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 160 BLR Belarus
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 161 GUY Guyana
    {2, {MAPCODE_ALPHABET_LAO, MAPCODE_ALPHABET_ROMAN}}, // 162 LAO Laos
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 163 ROU Romania
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 164 GHA Ghana
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 165 UGA Uganda
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 166 GBR United Kingdom
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 167 GIN Guinea
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 168 ECU Ecuador
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 169 ESH Western Sahara
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 170 GAB Gabon
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 171 NZL New Zealand
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 172 BFA Burkina Faso
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 173 PHL Philippines the
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 174 ITA Italy
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 175 OMN Oman
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 176 POL Poland
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 177 CIV Ivory Coast
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 178 NOR Norway
    {3, {MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_CHINESE}}, // 179 MYS Malaysia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 180 VNM Vietnam
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 181 FIN Finland
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 182 COG Congo-Brazzaville
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 183 DEU Germany
    {2, {MAPCODE_ALPHABET_KATAKANA, MAPCODE_ALPHABET_ROMAN}}, // 184 JPN Japan
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 185 ZWE Zimbabwe
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 186 PRY Paraguay
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 187 IRQ Iraq
    {3, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_TIFINAGH}}, // 188 MAR Morocco
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 189 UZB Uzbekistan
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 190 SWE Sweden
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 191 PNG Papua New Guinea
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 192 CMR Cameroon
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 193 TKM Turkmenistan
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 194 ESP Spain
    {2, {MAPCODE_ALPHABET_THAI, MAPCODE_ALPHABET_ROMAN}}, // 195 THA Thailand
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 196 YEM Yemen
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 197 FRA France
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 198 ALA Aaland Islands
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 199 KEN Kenya
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 200 BWA Botswana
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 201 MDG Madagascar
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 202 UKR Ukraine
    {2, {MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_ARABIC}}, // 203 SSD South Sudan
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 204 CAF Central African Republic
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 205 SOM Somalia
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 206 AFG Afghanistan
    {2, {MAPCODE_ALPHABET_BURMESE, MAPCODE_ALPHABET_ROMAN}}, // 207 MMR Myanmar
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 208 ZMB Zambia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 209 CHL Chile
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 210 TUR Turkey
    {3, {MAPCODE_ALPHABET_GURMUKHI, MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 211 PAK Pakistan
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 212 MOZ Mozambique
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 213 NAM Namibia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 214 VEN Venezuela
    {2, {MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_ARABIC}}, // 215 NGA Nigeria
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 216 TZA Tanzania
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 217 EGY Egypt
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 218 MRT Mauritania
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 219 BOL Bolivia
    {3, {MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_AMHARIC, MAPCODE_ALPHABET_ARABIC}}, // 220 ETH Ethiopia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 221 COL Colombia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 222 ZAF South Africa
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 223 MLI Mali
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 224 AGO Angola
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 225 NER Niger
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 226 TCD Chad
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 227 PER Peru
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 228 MNG Mongolia
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 229 IRN Iran
    {3, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_TIFINAGH}}, // 230 LBY Libya
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 231 SDN Sudan
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 232 IDN Indonesia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 233 MX-DIF Federal District, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 234 MX-TLA Tlaxcala, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 235 MX-MOR Morelos, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 236 MX-AGU Aguascalientes, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 237 MX-CL Colima, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 238 MX-QUE Queretaro, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 239 MX-HID Hidalgo, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 240 MX-ME Mexico State, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 241 MX-TAB Tabasco, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 242 MX-NAY Nayarit, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 243 MX-GUA Guanajuato, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 244 MX-PUE Puebla, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 245 MX-YUC Yucatan, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 246 MX-ROO Quintana Roo, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 247 MX-SIN Sinaloa, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 248 MX-CAM Campeche, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 249 MX-MIC Michoacan, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 250 MX-SLP San Luis Potosi, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 251 MX-GRO Guerrero, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 252 MX-NLE Nuevo Leon, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 253 MX-BCN Baja California, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 254 MX-VER Veracruz, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 255 MX-CHP Chiapas, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 256 MX-BCS Baja California Sur, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 257 MX-ZAC Zacatecas, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 258 MX-JAL Jalisco, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 259 MX-TAM Tamaulipas, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 260 MX-OAX Oaxaca, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 261 MX-DUR Durango, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 262 MX-COA Coahuila, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 263 MX-SON Sonora, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 264 MX-CHH Chihuahua, Mexico
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 265 GRL Greenland
    {2, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN}}, // 266 SAU Saudi Arabia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 267 COD Congo-Kinshasa
    {3, {MAPCODE_ALPHABET_ARABIC, MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_TIFINAGH}}, // 268 DZA Algeria
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 269 KAZ Kazakhstan
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 270 ARG Argentina
    {3, {MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_GUJARATI, MAPCODE_ALPHABET_ROMAN}}, // 271 IN-DD Daman and Diu
    {3, {MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_GUJARATI, MAPCODE_ALPHABET_ROMAN}}, // 272 IN-DN Dadra and Nagar Haveli
    {3, {MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_GURMUKHI}}, // 273 IN-CH Chandigarh
    {3, {MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_BENGALI}}, // 274 IN-AN Andaman and Nicobar
    {3, {MAPCODE_ALPHABET_MALAYALAM, MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_DEVANAGARI}}, // 275 IN-LD Lakshadweep
    {3, {MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_GURMUKHI, MAPCODE_ALPHABET_ROMAN}}, // 276 IN-DL Delhi, National Capital Territory of
    {2, {MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_DEVANAGARI}}, // 277 IN-ML Meghalaya
    {2, {MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_DEVANAGARI}}, // 278 IN-NL Nagaland
    {3, {MAPCODE_ALPHABET_BENGALI, MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_ROMAN}}, // 279 IN-MN Manipur
    {3, {MAPCODE_ALPHABET_BENGALI, MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_ROMAN}}, // 280 IN-TR Tripura
    {2, {MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_ROMAN}}, // 281 IN-MZ Mizoram
    {2, {MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_ROMAN}}, // 282 IN-SK Sikkim
    {3, {MAPCODE_ALPHABET_GURMUKHI, MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_ROMAN}}, // 283 IN-PB Punjab
    {3, {MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_GURMUKHI, MAPCODE_ALPHABET_ROMAN}}, // 284 IN-HR Haryana
    {2, {MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_DEVANAGARI}}, // 285 IN-AR Arunachal Pradesh
    {3, {MAPCODE_ALPHABET_BENGALI, MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_DEVANAGARI}}, // 286 IN-AS Assam
    {2, {MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_ROMAN}}, // 287 IN-BR Bihar
    {2, {MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_ROMAN}}, // 288 IN-UT Uttarakhand
    {2, {MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_ROMAN}}, // 289 IN-GA Goa
    {3, {MAPCODE_ALPHABET_MALAYALAM, MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_DEVANAGARI}}, // 290 IN-KL Kerala
    {3, {MAPCODE_ALPHABET_TAMIL, MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_ROMAN}}, // 291 IN-TN Tamil Nadu
    {2, {MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_ROMAN}}, // 292 IN-HP Himachal Pradesh
    {3, {MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_GURMUKHI, MAPCODE_ALPHABET_ROMAN}}, // 293 IN-JK Jammu and Kashmir
    {2, {MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_ROMAN}}, // 294 IN-CT Chhattisgarh
    {3, {MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_BENGALI, MAPCODE_ALPHABET_ROMAN}}, // 295 IN-JH Jharkhand
    {3, {MAPCODE_ALPHABET_KANNADA, MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_ROMAN}}, // 296 IN-KA Karnataka
    {2, {MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_ROMAN}}, // 297 IN-RJ Rajasthan
    {3, {MAPCODE_ALPHABET_ODIA, MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_DEVANAGARI}}, // 298 IN-OR Odisha
    {3, {MAPCODE_ALPHABET_GUJARATI, MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_DEVANAGARI}}, // 299 IN-GJ Gujarat
    {3, {MAPCODE_ALPHABET_BENGALI, MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_DEVANAGARI}}, // 300 IN-WB West Bengal
    {2, {MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_ROMAN}}, // 301 IN-MP Madhya Pradesh
    {3, {MAPCODE_ALPHABET_TELUGU, MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_ROMAN}}, // 302 IN-TG Telangana
    {3, {MAPCODE_ALPHABET_TELUGU, MAPCODE_ALPHABET_ROMAN, MAPCODE_ALPHABET_DEVANAGARI}}, // 303 IN-AP Andhra Pradesh
    {2, {MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_ROMAN}}, // 304 IN-MH Maharashtra
    {2, {MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_ROMAN}}, // 305 IN-UP Uttar Pradesh
    {3, {MAPCODE_ALPHABET_MALAYALAM, MAPCODE_ALPHABET_TELUGU, MAPCODE_ALPHABET_DEVANAGARI}}, // 306 IN-PY Puducherry
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 307 AU-NSW New South Wales, Australia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 308 AU-ACT Australian Capital Territory, Australia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 309 AU-JBT Jervis Bay Territory, Australia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 310 AU-NT Northern Territory, Australia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 311 AU-SA South Australia, Australia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 312 AU-TAS Tasmania, Australia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 313 AU-VIC Victoria, Australia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 314 AU-WA Western Australia, Australia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 315 AU-QLD Queensland, Australia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 316 BR-DF Distrito Federal, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 317 BR-SE Sergipe, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 318 BR-AL Alagoas, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 319 BR-RJ Rio de Janeiro, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 320 BR-ES Espirito Santo, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 321 BR-RN Rio Grande do Norte, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 322 BR-PB Paraiba, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 323 BR-SC Santa Catarina, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 324 BR-PE Pernambuco, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 325 BR-AP Amapa, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 326 BR-CE Ceara, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 327 BR-AC Acre, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 328 BR-PR Parana, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 329 BR-RR Roraima, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 330 BR-RO Rondonia, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 331 BR-SP Sao Paulo, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 332 BR-PI Piaui, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 333 BR-TO Tocantins, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 334 BR-RS Rio Grande do Sul, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 335 BR-MA Maranhao, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 336 BR-GO Goias, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 337 BR-MS Mato Grosso do Sul, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 338 BR-BA Bahia, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 339 BR-MG Minas Gerais, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 340 BR-MT Mato Grosso, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 341 BR-PA Para, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 342 BR-AM Amazonas, Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 343 US-DC District of Columbia, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 344 US-RI Rhode Island, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 345 US-DE Delaware, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 346 US-CT Connecticut, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 347 US-NJ New Jersey, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 348 US-NH New Hampshire, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 349 US-VT Vermont, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 350 US-MA Massachusetts, Commonwealth of, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 351 US-HI Hawaii, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 352 US-MD Maryland, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 353 US-WV West Virginia, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 354 US-SC South Carolina, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 355 US-ME Maine, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 356 US-IN Indiana, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 357 US-KY Kentucky, Commonwealth of, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 358 US-TN Tennessee, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 359 US-VA Virginia, Commonwealth of, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 360 US-OH Ohio, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 361 US-PA Pennsylvania, Commonwealth of, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 362 US-MS Mississippi, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 363 US-LA Louisiana, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 364 US-AL Alabama, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 365 US-AR Arkansas, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 366 US-NC North Carolina, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 367 US-NY New York, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 368 US-IA Iowa, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 369 US-IL Illinois, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 370 US-GA Georgia, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 371 US-WI Wisconsin, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 372 US-FL Florida, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 373 US-MO Missouri, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 374 US-OK Oklahoma, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 375 US-ND North Dakota, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 376 US-WA Washington, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 377 US-SD South Dakota, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 378 US-NE Nebraska, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 379 US-KS Kansas, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 380 US-ID Idaho, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 381 US-UT Utah, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 382 US-MN Minnesota, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 383 US-MI Michigan, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 384 US-WY Wyoming, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 385 US-OR Oregon, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 386 US-CO Colorado, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 387 US-NV Nevada, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 388 US-AZ Arizona, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 389 US-NM New Mexico, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 390 US-MT Montana, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 391 US-CA California, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 392 US-TX Texas, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 393 US-AK Alaska, USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 394 CA-BC British Columbia, Canada
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 395 CA-AB Alberta, Canada
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 396 CA-ON Ontario, Canada
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 397 CA-QC Quebec, Canada
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 398 CA-SK Saskatchewan, Canada
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 399 CA-MB Manitoba, Canada
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 400 CA-NL Newfoundland and Labrador, Canada
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 401 CA-NB New Brunswick, Canada
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 402 CA-NS Nova Scotia, Canada
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 403 CA-PE Prince Edward Island, Canada
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 404 CA-YT Yukon, Canada
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 405 CA-NT Northwest Territories, Canada
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 406 CA-NU Nunavut, Canada
    {3, {MAPCODE_ALPHABET_DEVANAGARI, MAPCODE_ALPHABET_BENGALI, MAPCODE_ALPHABET_ROMAN}}, // 407 IND India
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 408 AUS Australia, Commonwealth of
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 409 BRA Brazil
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 410 USA USA
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 411 MEX Mexico
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 412 RU-MOW Moscow, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 413 RU-SPE Saint Petersburg, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 414 RU-KGD Kaliningrad Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 415 RU-IN Ingushetia, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 416 RU-AD Adygea Republic, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 417 RU-SE North Ossetia-Alania Republic, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 418 RU-KB Kabardino-Balkar Republic, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 419 RU-KC Karachay-Cherkess Republic, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 420 RU-CE Chechen Republic, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 421 RU-CU Chuvash Republic, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 422 RU-IVA Ivanovo Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 423 RU-LIP Lipetsk Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 424 RU-ORL Oryol Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 425 RU-TUL Tula Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 426 RU-BE Belgorod Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 427 RU-VLA Vladimir Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 428 RU-KRS Kursk Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 429 RU-KLU Kaluga Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 430 RU-TAM Tambov Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 431 RU-BRY Bryansk Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 432 RU-YAR Yaroslavl Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 433 RU-RYA Ryazan Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 434 RU-AST Astrakhan Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 435 RU-MOS Moscow Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 436 RU-SMO Smolensk Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 437 RU-DA Dagestan Republic, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 438 RU-VOR Voronezh Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 439 RU-NGR Novgorod Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 440 RU-PSK Pskov Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 441 RU-KOS Kostroma Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 442 RU-STA Stavropol Krai, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 443 RU-KDA Krasnodar Krai, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 444 RU-KL Kalmykia Republic, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 445 RU-TVE Tver Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 446 RU-LEN Leningrad Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 447 RU-ROS Rostov Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 448 RU-VGG Volgograd Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 449 RU-VLG Vologda Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 450 RU-MUR Murmansk Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 451 RU-KR Karelia Republic, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 452 RU-NEN Nenets Autonomous Okrug, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 453 RU-KO Komi Republic, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 454 RU-ARK Arkhangelsk Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 455 RU-MO Mordovia Republic, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 456 RU-NIZ Nizhny Novgorod Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 457 RU-PNZ Penza Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 458 RU-KI Kirov Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 459 RU-ME Mari El Republic, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 460 RU-ORE Orenburg Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 461 RU-ULY Ulyanovsk Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 462 RU-PM Perm Krai, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 463 RU-BA Bashkortostan Republic, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 464 RU-UD Udmurt Republic, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 465 RU-TA Tatarstan Republic, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 466 RU-SAM Samara Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 467 RU-SAR Saratov Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 468 RU-YAN Yamalo-Nenets, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 469 RU-KM Khanty-Mansi, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 470 RU-SVE Sverdlovsk Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 471 RU-TYU Tyumen Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 472 RU-KGN Kurgan Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 473 RU-CH Chelyabinsk Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 474 RU-BU Buryatia Republic, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 475 RU-ZAB Zabaykalsky Krai, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 476 RU-IRK Irkutsk Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 477 RU-NVS Novosibirsk Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 478 RU-TOM Tomsk Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 479 RU-OMS Omsk Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 480 RU-KK Khakassia Republic, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 481 RU-KEM Kemerovo Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 482 RU-AL Altai Republic, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 483 RU-ALT Altai Krai, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 484 RU-TY Tuva Republic, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 485 RU-KYA Krasnoyarsk Krai, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 486 RU-MAG Magadan Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 487 RU-CHU Chukotka Okrug, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 488 RU-KAM Kamchatka Krai, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 489 RU-SAK Sakhalin Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 490 RU-PO Primorsky Krai, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 491 RU-YEV Jewish Autonomous Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 492 RU-KHA Khabarovsk Krai, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 493 RU-AMU Amur Oblast, Russia
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 494 RU-SA Sakha Republic, Russia
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 495 CAN Canada
    {2, {MAPCODE_ALPHABET_CYRILLIC, MAPCODE_ALPHABET_ROMAN}}, // 496 RUS Russia
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 497 CN-SH Shanghai Municipality, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 498 CN-TJ Tianjin Municipality, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 499 CN-BJ Beijing Municipality, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 500 CN-HI Hainan Province, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 501 CN-NX Ningxia Hui Autonomous Region, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 502 CN-CQ Chongqing Municipality, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 503 CN-ZJ Zhejiang Province, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 504 CN-JS Jiangsu Province, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 505 CN-FJ Fujian Province, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 506 CN-AH Anhui Province, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 507 CN-LN Liaoning Province, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 508 CN-SD Shandong Province, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 509 CN-SX Shanxi Province, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 510 CN-JX Jiangxi Province, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 511 CN-HA Henan Province, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 512 CN-GZ Guizhou Province, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 513 CN-GD Guangdong Province, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 514 CN-HB Hubei Province, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 515 CN-JL Jilin Province, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 516 CN-HE Hebei Province, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 517 CN-SN Shaanxi Province, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 518 CN-NM Nei Mongol Autonomous Region, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 519 CN-HL Heilongjiang Province, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 520 CN-HN Hunan Province, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 521 CN-GX Guangxi Zhuang Autonomous Region, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 522 CN-SC Sichuan Province, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 523 CN-YN Yunnan Province, China
    {3, {MAPCODE_ALPHABET_TIBETAN, MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 524 CN-XZ Xizang Autonomous Region, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 525 CN-GS Gansu Province, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 526 CN-QH Qinghai Province, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 527 CN-XJ Xinjiang Uyghur Autonomous Region, China
    {2, {MAPCODE_ALPHABET_CHINESE, MAPCODE_ALPHABET_ROMAN}}, // 528 CHN China, People's Republic of
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 529 UMI United States Minor Outlying Islands
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 530 CPT Clipperton Island
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 531 ATA Antarctica
    {1, {MAPCODE_ALPHABET_ROMAN}}, // 532 AAA International
};

#ifdef __cplusplus
}
#endif

#endif // __MAPCODE_TERRITORY_ALPHABETS_H__

